# Generated by Django 4.0.8 on 2024-09-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('accessories', 'Accessories'), ('phones', 'Phones'), ('computers', 'Computers'), ('clothing', 'Clothing'), ('home_appliances', 'Home Appliances'), ('books', 'Books'), ('toys', 'Toys'), ('beauty', 'Beauty'), ('sports', 'Sports'), ('food', 'Food'), ('furniture', 'Furniture')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.store')),
            ],
        ),
    ]
